{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<form method="post" action={"/notification/settings/"|ezurl}>

    <section class="hgroup">
      <h1>{"Notification settings"|i18n('design/standard/notification')}</h1>
    </section>

    {let handlers=fetch('notification','handler_list')}

        <p>
            {section name=Handlers loop=$handlers}
            {if $Handlers:item.id_string|eq('ezcollaboration')}
                {include handler=$Handlers:item uri=concat( "design:notification/handler/",$Handlers:item.id_string,"/settings/edit.tpl")}
            {/if}
            {/section}
        </p>
    {/let}

    <div>
        <input class="button btn btn-success" type="submit" name="Store" value="{'Store'|i18n('design/standard/notification')}" />
    </div>
</form>
