{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute' html_class='full' placeholder=false()}
    <textarea maxlength="{openpaini('SensorConfig','TextMaxLength',300)}" {if $placeholder}placeholder="{$placeholder}"{/if} id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{$html_class} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_text_{$attribute.id}" cols="70" rows="{$attribute.contentclass_attribute.data_int1}">{$attribute.content|wash}</textarea>
{/default}

<script type="text/javascript">
$(document).ready(function(){ldelim}
$('#ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}').keyup(function () {ldelim}
    var left = {openpaini('SensorConfig','TextMaxLength',300)} - $(this).val().length;
    if (left < 0) {ldelim}
        left = 0;
    {rdelim}
    $('#{$attribute.contentclassattribute_id}-counter span').text(left);
{rdelim});
$('#ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}').trigger( 'keyup' );
{rdelim});
</script>